name: frontend
description: Hackathon CCR

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.4.0
  location: ^2.3.5
  flutter_polyline_points: ^0.1.0
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.10
  permission: ^0.1.7
  table_calendar: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/avatar.png
    - images/posto.jpg
    - images/logo-pink-way.png
    - images/posto-ccr.jpg
    - images/caminhoneira-loira.jpeg
    - images/autocuidado-1.jpg
    - images/ginecologista.jpg
    - images/nutricionista.jpg

fonts:
  - family: ShadowsIntoLight
    fonts:
      - asset: fonts/ShadowsIntoLight-Regular.ttf

  - family: SourceSansPro
    fonts:
      - asset: fonts/SourceSansPro-Regular.ttf
